### ISSUE TITLE
Install SirenofShame on Raspberry PI

### ISSUE THREAD

**Issue by johncjv** [AutomatedArchitecture/SirenOfShame#103]
Hi,

Would appreciate some help on using the Siren on Raspberry PI. Can someone tell me what is the problem?
I'm following this post to set up the things: 
http://blog.sirenofshame.com/2014/07/raspberry-pi-powered-siren-of-shame-via.html 

Here's that I get when running npm-install: 
pi@raspberrypi:~ $ node --version
v8.7.0
pi@raspberrypi:~ $ cd node-sos-client
pi@raspberrypi:~/node-sos-client $ npm install

> sos-device@0.0.1 install /home/pi/node-sos-client/node_modules/sos-device
> node-gyp rebuild

make: Entering directory '/home/pi/node-sos-client/node_modules/sos-device/build'
  CXX(target) Release/obj.target/sos/src/binding.o
In file included from ../src/binding.cpp:2:0:
../src/nodeSos.h:14:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> findDevice(const v8::Arguments& args);
                                            ^~~~~~~~~
../src/nodeSos.h:16:43: error: expected class-name before ‘{’ token
 class SosDevice : public node::ObjectWrap {
                                           ^
../src/nodeSos.h:24:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> readInfo(const v8::Arguments& args);
                                                   ^~~~~~~~~
../src/nodeSos.h:25:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> readLedPatterns(const v8::Arguments& args);
                                                          ^~~~~~~~~
../src/nodeSos.h:26:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> readAudioPatterns(const v8::Arguments& args);
                                                            ^~~~~~~~~
../src/nodeSos.h:27:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> sendControlPacket(const v8::Arguments& args);
                                                            ^~~~~~~~~
../src/binding.cpp: In function ‘void init(v8::Handle<v8::Object>)’:
../src/binding.cpp:7:21: error: ‘v8::HandleScope::HandleScope()’ is protected within this context
     v8::HandleScope scope;
                     ^~~~~
In file included from /home/pi/.node-gyp/8.7.0/include/node/node.h:63:0,
                 from ../src/nodeSos.h:2,
                 from ../src/binding.cpp:2:
/home/pi/.node-gyp/8.7.0/include/node/v8.h:874:13: note: declared protected here
   V8_INLINE HandleScope() {}
             ^~~~~~~~~~~
../src/binding.cpp:8:53: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&) {aka v8::Local<v8::Value> (*)(const int&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
     NODE_SET_METHOD(target, "findDevice", findDevice);
                                                     ^
In file included from ../src/nodeSos.h:2:0,
                 from ../src/binding.cpp:2:
/home/pi/.node-gyp/8.7.0/include/node/node.h:287:13: note:   initializing argument 3 of ‘void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^~~~~~~~~~~~~~~
sos.target.mk:96: recipe for target 'Release/obj.target/sos/src/binding.o' failed
make: *** [Release/obj.target/sos/src/binding.o] Error 1
make: Leaving directory '/home/pi/node-sos-client/node_modules/sos-device/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.41-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node-sos-client/node_modules/sos-device
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN sos-client@0.0.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sos-device@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sos-device@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-10-16T12_01_24_420Z-debug.log

**Comment by lprichar** [comment]
It's been so long since I've done that I can't recall the details, but that does sound familiar, like node was x86 and needed to be arm or something.  Did you try the subsequent section "Upgrading Node"?

**Comment by johncjv** [comment]
Yes I did try it and got the same version. Is there any command that could tell me if I have the good type of node in my path?
pi@raspberrypi:~/node-sos-client $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/pi/node-v0.10.2-linux-arm-pi/bin

**Comment by johncjv** [comment]
Hi,

I got it working by calling with the absolute path. Thanks.

Ionut.
