### ISSUE TITLE
TeamCity connection locking user account

### ISSUE THREAD

**Issue by Gerboa** [AutomatedArchitecture/SirenOfShame#104]
TeamCity is set up to use domain accounts and SoS is connecting with a specified account and password.

Where the user password has changed on their domain account, SoS is still using the old account details but this causes TC to attempt validation of the supplied details which after 5 failures locks the users domain account.

**Comment by lprichar** [comment]
Should be fixed.  I'd greatly appreciate it if you could verify and re-open if it isn't working.  I'll get a build out shortly.

**Comment by lprichar** [comment]
Published in 2.4.11 http://sirenofshame.com/Downloads/View?downloadId=48
