### ISSUE TITLE
'A build succeeds' rule is not always fired

### ISSUE THREAD

**Issue by TurboPablos** [AutomatedArchitecture/SirenOfShame#106]
Sometimes there is no sound after successfull build, so I assume, whole 'A build succeeds' rule is not always fired.

It seems to occur when the build was in failed state and after that- it was repaired (succesfull state).

**Comment by TurboPablos** [comment]
Any progress with it? ;)

**Comment by lprichar** [comment]
Wow, that's a bug you just found in 6 year old code!  The incorrect functionality was even documented in a unit test.  I was all ready to prove you wrong, but oh have I been humbled :).  Nice find!

**Comment by lprichar** [comment]
This fix should be live in 2.4.12: https://sirenofshame.com/Downloads
