### ISSUE TITLE
Can't connect to VSTS - 404 (Not Found)

### ISSUE THREAD

**Issue by ScottLangham** [AutomatedArchitecture/SirenOfShame#108]
I'm not too sure how to proceed, I've generated a PAT for the username field.

![image](https://user-images.githubusercontent.com/11654035/33075886-e1cc9848-cec2-11e7-82fc-30ac6d9f3796.png)

**Comment by lprichar** [comment]
What permissions did you grant your personal access token?  All scopes (to start)?  Have you tried specifying the project collection in the "Collection" text box?  If you don't have enough permission at the root level, then that might help.  Also, in the screenshot it looks like you didn't put in a password.  I'm assuming you cleared it for the purposes of the screenshot?

**Comment by lprichar** [comment]
Sorry it took so long to respond @ScottLangham, I was on Holiday.  Are you still game for troubleshooting or should I close this issue?

**Comment by lprichar** [comment]
Well, in case anyone else finds this page I updated the wiki on how to connect to VSTS and linked to it from the app.  The page is: https://github.com/AutomatedArchitecture/SirenOfShame/wiki/How-To-Connect-to-VSTS

**Comment by lprichar** [comment]
This fix should be live in 2.4.12: https://sirenofshame.com/Downloads
