### ISSUE TITLE
Account verification email not being sent

### ISSUE THREAD

**Issue by joshuablue** [AutomatedArchitecture/SirenOfShame#119]
Please provide as much info from below as possible:

### Steps to reproduce

1. Go to http://sirenofshame.com/Account/Unverified
2. Click resend verification
3. Email never comes

### Expected behavior

I should get an account verification email

### Actual behavior

nothing

### Configuration
Your website

**Sos Version:** 

[From the 'What's Going On?' button]

**Build Server:** 
- [ ] AppVeryor
- [ ] Bamboo
- [ ] CruiseControl.Net
- [ ] Jenkins/Hudson
- [ ] Team City
- [ ] TFS 2015+
- [ ] TFS 2010-2013 (xaml build definition)
- [ ] Travis

**Any Relevant Logs**

See [screenshot](http://blog.sirenofshame.com/2012/01/how-to-report-errors.html) for how to retrieve

**Comment by lprichar** [comment]
Hey @joshuablue I just went through the process and I successfully received the original e-mail and a 2nd one after clicking resend on the page you identified.  Both e-mails went to my junk folder, could that have been an issue for you?  

In the process I did discover that we were using a deprecated version of ReCaptcha that was just shut down last week, and so I fixed that.  Could that have been the problem?

If it's definitely not in your spam folder and the ReCaptcha issue wasn't to blame, could you please send an e-mail to support at our domain name with your requested username and/or e-mail used to register?  We can manually enable your account and do a little more research that way.

**Comment by joshuablue** [comment]
It was in my spam folder, sorry about that!
