### ISSUE TITLE
TeamCity: Issues with multiple agents running the same build

### ISSUE THREAD

**Issue by BubbaFatAss** [AutomatedArchitecture/SirenOfShame#120]
Please provide as much info from below as possible:
It looks like we run into problems when our build farm is running the same build on multiple agents.  The UI goes crazy and attempts to rebuild all the build boxes every time a server update happens, and fails to detect that some of them really are already in the list.  I've grabbed the source, and a very quick poke at the code indicated that SirenOfShame.Lib.Util.BuildStatusUtil.Merge isn't correctly merging the team city build statuses.

![image](https://user-images.githubusercontent.com/1834077/48500518-f28aed80-e832-11e8-9e1a-696855c84c24.png)

Demonstrates what it looks like when things are going wrong.  At this point in time, the profile build config was running on three agents at once, yet there's already many more than this visible here.

I'll try and come up with a fix, but I'm unsure what the expected behaviour is here - should multiple builds be listed, or should we just keep the box in the "in progress" state until all builds end?

### Steps to reproduce

1. Have multiple TeamCity agents run the same build.
2. Have SoS monitor the build, and open the main window.
3. Observe that the number of builds reported in the SoS gui grows exponentially to the point where the app becomes unresponsive or crashes.

### Expected behavior

Builds remain in the "in progress" state until all have completed.

### Actual behavior

The number of builds reported in the SoS gui grows exponentially to the point where the app becomes unresponsive or crashes.

### Configuration
**Sos Version:** 

2.4.12 (but also occurs on HEAD revision from Github)

**Build Server:** 
- [ x ] Team City

**Any Relevant Logs**
I've not attached any, but can if you think this would be helpful

**Comment by lprichar** [comment]
This appears to be resolved, thanks for your contribution.  I just need to renew the code signing cert then I'll get a new build out with this in it.

**Comment by lprichar** [comment]
Feature published in v2.4.13: https://sirenofshame.com/Downloads
