### ISSUE TITLE
Window shrinks to 0x0 px after load.

### ISSUE THREAD

**Issue by fsuk** [AutomatedArchitecture/SirenOfShame#124]
Please provide as much info from below as possible:

### Steps to reproduce
1. Windows 7
2. Start Application
3. Wait until window has loaded

### Expected behavior
Window should remain at last used size

### Actual behavior

The window initially loads correctly but after a second or two is automatically resized such that only the title bar and window buttons are visible
![1](https://user-images.githubusercontent.com/22119319/64104173-aa11d180-cd6b-11e9-9a2d-6f1b8a1c8952.PNG)

### Configuration

**Sos Version:** 
2.4.13

**Build Server:** 
- [ ] AppVeryor
- [ ] Bamboo
- [ ] CruiseControl.Net
- [ ] Jenkins/Hudson
- [ ] Team City
- [X] TFS 2015+
- [ ] TFS 2010-2013 (xaml build definition)
- [ ] Travis

**Any Relevant Logs**

See [screenshot](http://blog.sirenofshame.com/2012/01/how-to-report-errors.html) for how to retrieve

**Comment by lprichar** [comment]
Confirmed.  Thanks for reporting this @fsuk , I'll look into it shortly.
