### ISSUE TITLE
ability to resize build column in full screen

### ISSUE THREAD

**Issue by sosfeature** [AutomatedArchitecture/SirenOfShame#33]
we have a large screen showing the full screen of our builds.  some of our build names have longer names than fit in the Build Name column and the Comment column usually has room on the right side of the screen for more text.  Ideally we'd be able to control the size of the build column so we can see which build it is.  Obviously we can rename to use shorter build names but we'd prefer not to (especially there is plenty of screen real estate)

e.g. build names Acceptance.<Company>.<Product>.<Environment> (most important parts of the names are cut off).  g

great product otherwise!

**Comment by lprichar** [comment]
This was fixed in 2.4.0 http://sirenofshame.com/downloads/View?downloadId=34.  You can now hit Ctrl+ to increase sizes and Ctrl- to decrease sizes.
