### ISSUE TITLE
Is there a way to only show builds?

### ISSUE THREAD

**Issue by pvandervelde** [AutomatedArchitecture/SirenOfShame#46]
I don't really care much for the News and Leaders section so is it possible to turn those off? As a side note is there a way to have different pictures (e.g. gravatar or something like that). The cats and dogs are getting on my nerves :(

**Comment by lprichar** [comment]
Custom images was added in 2.4.1 and 2.4.2 http://sirenofshame.com/downloads/View?downloadId=36
