### ISSUE TITLE
Build server unavailable

### ISSUE THREAD

**Issue by tommc3** [AutomatedArchitecture/SirenOfShame#62]
After a recent windows upgrade this message appeared.  Prior to the upgrade SOS was working.  I verified the URL is available via other tools (browser).
![sos error](https://cloud.githubusercontent.com/assets/410664/10006162/306cb0d2-6070-11e5-8b51-1c124bc2fedf.PNG)

**Comment by tommc3** [comment]
Also note I'm trying to connect to a Jenkins server running on port 8080 and I'm running version 2.3.10 on Windows 7.  My guess is this something changed in the networking when I ran windows upgrades.  I also tried on Windows 8.1 with the same result.

**Comment by tommc3** [comment]
Rebooted and now it's working?

**Comment by lprichar** [comment]
Well, glad it's working, although random unresolved errors bother me.  If it happens again would you mind checking out Fiddler or Wireshark to compare what the desktop app is doing vs what your regular browser is doing?
