### ISSUE TITLE
Not able to download SirenOfShame

### ISSUE THREAD

**Issue by SushantKadam008** [AutomatedArchitecture/SirenOfShame#63]
Hi,
I am not bale to download the github project.
How to configure the project with VSO ?

**Comment by mightymuke** [comment]
Hi,

Can you please elaborate on why you cant download the github project?

Thanks

**Comment by SushantKadam008** [comment]
Hi 
I am able to download the project.
But I am not able to configure VSO on SoS.

I enter all the credentials and it does not show the status 

![sos_vso connection issue](https://cloud.githubusercontent.com/assets/7605326/11454645/47e58690-9634-11e5-8f32-cefaa2b566c7.png)

**Comment by mightymuke** [comment]
Thanks for the clarification.

Unfortunately I'm not a TFS expert so I'll have to leave you to those who are.
It may help though if you can upload anything suspicious from the logs (http://blog.sirenofshame.com/2012/01/how-to-report-errors.html).

Thanks.
