### ISSUE TITLE
Not able to configure VSO on SoS

### ISSUE THREAD

**Issue by SushantKadam008** [AutomatedArchitecture/SirenOfShame#64]
I am not able to configure VSO on SoS.
I enter all the credentials and it does not show the status.

![sos_vso connection issue](https://cloud.githubusercontent.com/assets/7605326/11456409/1621dda8-9688-11e5-9b68-11a8b30f165d.png)

**Comment by lprichar** [comment]
Hi @SushantKadam008.  Two questions.

1. It looks like it was you that posted on the relevant blog (http://blog.sirenofshame.com/2014/04/visual-studio-online.html), but just to confirm, did you enable alternate credentials?  What url are you using?  Does it follow the form https://[myproject]/visualstudio.com/.

2. Can you please take a look through your logs and post anything that looks relevant: http://blog.sirenofshame.com/2012/01/how-to-report-errors.html.  If you aren't comfortable posting publicly you can also send it to support at our domain name.

Thanks,
Lee

**Comment by SushantKadam008** [comment]
HI Lee,
Yes I did enable alternate credentials in VSO and used the https format.
I will check the log and inform you accordingly

Thanks,
Sushant

**Comment by lprichar** [comment]
I think this should be fixed with the new TFS 2015 build support.  This is in 2.4.5 http://sirenofshame.com/downloads/View?downloadId=40.  Please re-open if error is still happening.
