### ISSUE TITLE
TFS 2015 Api requires high level access

### ISSUE THREAD

**Issue by spam1923** [AutomatedArchitecture/SirenOfShame#82]
I was unable to hit the TFS Api endpoint for "_apis/projectcollections" as that requires "Edit Instance Level" permissions. In a large organization it would be difficult to get a user that has permissions to edit all instances. Suggestion to get around it would be to allow the option for a user to enter a Specific Collection Name that they have access to. I tested this by hardcoding the TfsRestServices.TfsJsonService.GetProjectCollections to just return the one collection I have access to. Everything worked as expected.

**Comment by lprichar** [comment]
Nice suggestion!  Hadn't though of that scenario.  Will add to the queue.

**Comment by spam1923** [comment]
Thank you for the quick response! Let me know if you need me to test any changes out. I can pull down a different branch if you would like.

**Comment by lprichar** [comment]
Should be resolved by PR #90
