### ISSUE TITLE
403 when connecting to on-prem TFS 2015

### ISSUE THREAD

**Issue by amccool** [AutomatedArchitecture/SirenOfShame#88]
When connecting to a on premise TFS 2015 server and supplying AD credentials, received a 
`Response status code does not indicate success: 403 (Forbidden).`

**Comment by sarahkMayberry** [comment]
I am also receiving this error do you guys have a range of IP address that we can allow through our firewall?

**Comment by lprichar** [comment]
Which TFS plugin are you using?  The TFS2015+ one or the older one?  If you have a XAML-based definition you can try the older one, although I'd like to solve the root problem.  Can you navigate to http://[server]/_apis/projectcollections in a browser or does that also give you 403?  I'm wondering if this might be related to Issue #82.

**Comment by sarahkMayberry** [comment]
I am using the TFS2015+ when i go to this url i do not have access I am going to go get the "edit instance level information" permission and retry will update if this resolves the issue

**Comment by sarahkMayberry** [comment]
the permission change also resolved this error thanks!

**Comment by lprichar** [comment]
Excellent.  @amccool can you please verify if that fixes it for you?  If so I'll interpret this issue as "make a better error message when more permissions are needed" which will still be useful even when Issue #82 has been resolved.

**Comment by amccool** [comment]
@lprichar sorry to say I have moved to different tooling.  Perhaps @sarahkMayberry can own this issue for resolution?

**Comment by lprichar** [comment]
Should be resolved by PR #90

**Comment by Grifplex** [comment]
I've been trying to configure SoS and have not been able to connect to my companies' on premise TFS 2015 server. I get the `Response status code does not indicate success: 403 (Forbidden).` I can, however, connect using the old 2010 XAML type, but non of our builds use it and IT will not change the permissions on the server. 
Each attempt of http://<tfs_server>:8080/tfs or http://<tfs_server>:8080/tfs/DefaultCollection has returned the '403 (Forbidden)' when trying to connect.
What is the procedure to specify a TFS project collection directly and can the TFS 2015 connection use windows log-in information like the TFS 2010?

**Comment by lprichar** [comment]
@Grifplex Can you add a personal access token and log in with that?  If so, the only scope it should need is "Build (read)".  Or is that only a VSTS feature?

Can you verify the REST api is working by logging in with a browser to https://<tfs_server>:8080/_apis/projects or https://<tfs_server>:8080/tfs/_apis/projects?

You already used correctly the procedure to specify a TFS project collection: http://<tfs_server>:8080/tfs/DefaultCollection, although I suppose you could try without the "/tfs".

As far as I know TFS 2015 cannot use the same authentication technique as TFS 2010 since that was using SOAP endpoints.

**Comment by lprichar** [comment]
@Grifplex Looks like I omitted that bug fix in 2.4.9.  Can you please try again with 2.4.10 at http://sirenofshame.com/downloads.

**Comment by Grifplex** [comment]
Thanks! the update is working!
