### ISSUE TITLE
Feature Request:  Support Unicode characters

### ISSUE THREAD

**Issue by careLearning** [AutomatedArchitecture/SirenOfShame#95]
We use source code with Turkish authors (see https://github.com/aspnetboilerplate/aspnetboilerplate) 

Minor grievance their commits sometimes looks garbled see attached image, which includes the author's name.

![image](https://cloud.githubusercontent.com/assets/15213955/26588798/55257018-4524-11e7-960e-7005c985c9b6.png)

**Comment by lprichar** [comment]
Cool project!  Do you happen to know if the API to the CI server you're using is returning names in unicode?  What CI server is it?

**Comment by careLearning** [comment]
@lprichar thanks for the quick reply.   We are using on-premises Atlassian Bamboo 5.13.2 and Atlassian Bitbucket v4.10.1 as the source code control.    The web-based GUI for both applications render the characters for the author's name correctly.   See 
![image](https://cloud.githubusercontent.com/assets/15213955/26631214/040f5ba8-45d8-11e7-98fc-90bfb049077d.png)

Any ideas on the best way to verify that the API is indeed returning unicode characters?

**Comment by lprichar** [comment]
Sorry it took so long to resolve this.  I should have an official build with this fix in a couple of days.

**Comment by lprichar** [comment]
This fix should be live in 2.4.12: https://sirenofshame.com/Downloads
