### ISSUE TITLE
Cannot connect to TFS vNext (TFS 2015+)

### ISSUE THREAD

**Issue by CJBS** [AutomatedArchitecture/SirenOfShame#99]
I am able to connect to TFS for XAML builds. My network login works OK.

I am able to connect to TFS's 2015 vNext to see build status using the (competing) CatLight tool (). Thus, there does not seem to be a problem with the configuration of login API endpoints on the TFS server.

I had the administrator of our TFS system download and install SirenOfShame and log in using administrator credentials, and he was not able to log in successfully.

I get a 403/forbidden error when connecting.

I know that the URL is correct, because when I use an invalid URL, it gives me 404/notFound.

I have tried with different flavours of URL (including IP address, and domain name). I have tried using various flavours of user name (e.g. DOMAIN\user, user@DOMAIN, user@DOMAIN.company.com, user). I have tried using both password, and TFS personal access token. All give the 403/forbidden response.

All of this occurs on the Configure Server screen after selecting CI Server "Microsoft TFS 2015+", using a TFS URL like "http://10.0.0.1:8080/tfs" or "http://tfsserver:8080/tfs"

![image](https://user-images.githubusercontent.com/29615179/27409558-e4a6fad0-5696-11e7-81c6-c13672733452.png)

**Comment by lprichar** [comment]
Thanks for the screenshot, that made me realize you're missing the bits that should have solved the 403 issue.  I must not have included that in 2.4.9 after all.   

I just released Version 2.4.10.  It has a separate textbox for entering the project collection.  Can you please try with that?  http://sirenofshame.com/downloads

**Comment by CJBS** [comment]
Great; I tried that and it works. Thanks for being so responsive!
